name: File checks
on:
  push: []
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
      with:
        # Checkout the head ref instead of the PR branch that github creates.
        ref: ${{ github.head_ref }}
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Check Directory
      working-directory: ./.github/workflows
      run: ls -al 
    - name: Install and build
      working-directory: ./.github/workflows
      run: npm ci
    - name: Run status checks
      run: node checks.js
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
